### ISSUE TITLE
Fixes for balance rounding bugs

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/efectivo-web#20]
- [ ] Make it so that send function subtracts gas from amount sent
- [x] Round balance down to nearest cent

- [x] If balance is less than one cent but more than zero, display four decimal places. i.e. $0.002431919 -> $0.0024

**Comment by sebohe** [comment]
Just want to write down what we spoke about yesterday:

We are going to subtract the transaction cost from the display value. basically assuming that the transaction cost is never part of the balance of the user.
