### ISSUE TITLE
COP display on tx history screen

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/efectivo-web#32]
![image](https://user-images.githubusercontent.com/1335122/54950020-9ed59280-4efd-11e9-9455-276653b04356.png)

Estimate: 1 hour

**Comment by sebohe** [comment]
Started here: https://github.com/althea-mesh/efectivo-web/commit/ce923cd3a013957ff9d7a682cffc62bf2a878331

Finished here: https://github.com/althea-mesh/efectivo-web/commit/994a7afa7fddc3ab4b81d9a607d3cdbc71b3c662
